// frontend/src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/*
        ADD THESE CLASSES:
        - bg-gray-50: Sets a light gray background in light mode.
        - dark:bg-black: Sets a black background in dark mode.
        - text-gray-900: Sets a dark text color in light mode.
        - dark:text-gray-100: Sets a light text color in dark mode.
      */}
      <body className="bg-gray-50 dark:bg-black text-gray-900 dark:text-gray-100">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
