# Generated by Django 5.2.7 on 2025-10-12 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('primary_body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('weekday_lifestyle', models.CharField(blank=True, max_length=50, null=True)),
                ('weekend_lifestyle', models.CharField(blank=True, max_length=100, null=True)),
                ('wardrobe_percentages', models.JSONField(blank=True, default=dict)),
                ('style_scores', models.JSONField(blank=True, default=dict)),
                ('top_three_styles', models.CharField(blank=True, max_length=150, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
