# Generated by Django 5.2.7 on 2025-10-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=1024)),
                ('category', models.CharField(max_length=50)),
                ('color_name', models.CharField(max_length=50)),
                ('color_family', models.CharField(max_length=50)),
                ('is_neutral', models.BooleanField(default=False)),
                ('season', models.CharField(max_length=50)),
                ('fit', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=255)),
                ('body_type', models.CharField(max_length=255)),
                ('lifestyle', models.CharField(max_length=255)),
                ('utility', models.CharField(max_length=255)),
            ],
        ),
    ]
